<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_ui_message">
    <sys_ui_message action="INSERT_OR_UPDATE">
        <application/>
        <code/>
        <commented_message/>
        <key>job_connection_error</key>
        <language>en</language>
        <message>There was an error connecting to the remote instance.</message>
        <sys_class_name>sys_ui_message</sys_class_name>
        <sys_created_by>tom.hauri</sys_created_by>
        <sys_created_on>2024-03-16 10:51:14</sys_created_on>
        <sys_id>ffd040641bc50e1030d6fdd49b4bcb00</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>job_connection_error</sys_name>
        <sys_package display_value="Instance Sync" source="x_snc_instanc_sync">5dfc37d71b780a1030d6fdd49b4bcb91</sys_package>
        <sys_policy/>
        <sys_scope display_value="Instance Sync">5dfc37d71b780a1030d6fdd49b4bcb91</sys_scope>
        <sys_update_name>sys_ui_message_ffd040641bc50e1030d6fdd49b4bcb00</sys_update_name>
        <sys_updated_by>tom.hauri</sys_updated_by>
        <sys_updated_on>2024-03-16 10:51:14</sys_updated_on>
    </sys_ui_message>
</record_update>
